apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-back-deployment-autoscaling
  labels:
    apps: my-backend-deployment

spec:
  selector:
    matchLabels:
      project: fastify-autoscaling

  template:
    metadata:
      labels:
        project: fastify-autoscaling # Service will look for those PODS Labels !!!
    spec:
      containers:
        - name: fastify-autoscaling-backend
          image: fedok/k8snode:latest
          ports:
            - containerPort: 3000


---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-back-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaing-pod-service
  labels:
    env: prod
    owner: fedok
spec:
  selector:
    project: fastify-autoscaling # Selecting PODS with those Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 6754 # Port on Load Balancer
      targetPort: 3000 # Port on POD
  type: LoadBalancer